/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaterSoftenerForApartmentRouteImport } from './routes/water-softener-for-apartment'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as SparesKitRouteImport } from './routes/spares-kit'
import { Route as SoftwatercareVsShowerstickVsAgRouteImport } from './routes/softwatercare-vs-showerstick-vs-ag'
import { Route as ShowerstickAlternativeRouteImport } from './routes/showerstick-alternative'
import { Route as ShowerHeadWaterSoftenerRouteImport } from './routes/shower-head-water-softener'
import { Route as ShowerFilterVsWaterSoftenerRouteImport } from './routes/shower-filter-vs-water-softener'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as RedditShowerWaterSoftenerRouteImport } from './routes/reddit-shower-water-softener'
import { Route as PreventLimescaleInShowerRouteImport } from './routes/prevent-limescale-in-shower'
import { Route as PortableWaterSoftenerForShowerRouteImport } from './routes/portable-water-softener-for-shower'
import { Route as JolieAlternativeForHardWaterRouteImport } from './routes/jolie-alternative-for-hard-water'
import { Route as DoShowerFiltersWorkForHardWaterRouteImport } from './routes/do-shower-filters-work-for-hard-water'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CanopyAlternativeForHardWaterRouteImport } from './routes/canopy-alternative-for-hard-water'
import { Route as BestShowerWaterSoftenerRouteImport } from './routes/best-shower-water-softener'
import { Route as AriusVsAgWaterSoftenerRouteImport } from './routes/arius-vs-ag-water-softener'
import { Route as IndexRouteImport } from './routes/index'

const WaterSoftenerForApartmentRoute =
  WaterSoftenerForApartmentRouteImport.update({
    id: '/water-softener-for-apartment',
    path: '/water-softener-for-apartment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const SparesKitRoute = SparesKitRouteImport.update({
  id: '/spares-kit',
  path: '/spares-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwatercareVsShowerstickVsAgRoute =
  SoftwatercareVsShowerstickVsAgRouteImport.update({
    id: '/softwatercare-vs-showerstick-vs-ag',
    path: '/softwatercare-vs-showerstick-vs-ag',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerstickAlternativeRoute = ShowerstickAlternativeRouteImport.update({
  id: '/showerstick-alternative',
  path: '/showerstick-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowerHeadWaterSoftenerRoute = ShowerHeadWaterSoftenerRouteImport.update({
  id: '/shower-head-water-softener',
  path: '/shower-head-water-softener',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowerFilterVsWaterSoftenerRoute =
  ShowerFilterVsWaterSoftenerRouteImport.update({
    id: '/shower-filter-vs-water-softener',
    path: '/shower-filter-vs-water-softener',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const RedditShowerWaterSoftenerRoute =
  RedditShowerWaterSoftenerRouteImport.update({
    id: '/reddit-shower-water-softener',
    path: '/reddit-shower-water-softener',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreventLimescaleInShowerRoute =
  PreventLimescaleInShowerRouteImport.update({
    id: '/prevent-limescale-in-shower',
    path: '/prevent-limescale-in-shower',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortableWaterSoftenerForShowerRoute =
  PortableWaterSoftenerForShowerRouteImport.update({
    id: '/portable-water-softener-for-shower',
    path: '/portable-water-softener-for-shower',
    getParentRoute: () => rootRouteImport,
  } as any)
const JolieAlternativeForHardWaterRoute =
  JolieAlternativeForHardWaterRouteImport.update({
    id: '/jolie-alternative-for-hard-water',
    path: '/jolie-alternative-for-hard-water',
    getParentRoute: () => rootRouteImport,
  } as any)
const DoShowerFiltersWorkForHardWaterRoute =
  DoShowerFiltersWorkForHardWaterRouteImport.update({
    id: '/do-shower-filters-work-for-hard-water',
    path: '/do-shower-filters-work-for-hard-water',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CanopyAlternativeForHardWaterRoute =
  CanopyAlternativeForHardWaterRouteImport.update({
    id: '/canopy-alternative-for-hard-water',
    path: '/canopy-alternative-for-hard-water',
    getParentRoute: () => rootRouteImport,
  } as any)
const BestShowerWaterSoftenerRoute = BestShowerWaterSoftenerRouteImport.update({
  id: '/best-shower-water-softener',
  path: '/best-shower-water-softener',
  getParentRoute: () => rootRouteImport,
} as any)
const AriusVsAgWaterSoftenerRoute = AriusVsAgWaterSoftenerRouteImport.update({
  id: '/arius-vs-ag-water-softener',
  path: '/arius-vs-ag-water-softener',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arius-vs-ag-water-softener': typeof AriusVsAgWaterSoftenerRoute
  '/best-shower-water-softener': typeof BestShowerWaterSoftenerRoute
  '/canopy-alternative-for-hard-water': typeof CanopyAlternativeForHardWaterRoute
  '/contact': typeof ContactRoute
  '/do-shower-filters-work-for-hard-water': typeof DoShowerFiltersWorkForHardWaterRoute
  '/jolie-alternative-for-hard-water': typeof JolieAlternativeForHardWaterRoute
  '/portable-water-softener-for-shower': typeof PortableWaterSoftenerForShowerRoute
  '/prevent-limescale-in-shower': typeof PreventLimescaleInShowerRoute
  '/reddit-shower-water-softener': typeof RedditShowerWaterSoftenerRoute
  '/returns': typeof ReturnsRoute
  '/setup': typeof SetupRoute
  '/shipping': typeof ShippingRoute
  '/shower-filter-vs-water-softener': typeof ShowerFilterVsWaterSoftenerRoute
  '/shower-head-water-softener': typeof ShowerHeadWaterSoftenerRoute
  '/showerstick-alternative': typeof ShowerstickAlternativeRoute
  '/softwatercare-vs-showerstick-vs-ag': typeof SoftwatercareVsShowerstickVsAgRoute
  '/spares-kit': typeof SparesKitRoute
  '/thanks': typeof ThanksRoute
  '/water-softener-for-apartment': typeof WaterSoftenerForApartmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arius-vs-ag-water-softener': typeof AriusVsAgWaterSoftenerRoute
  '/best-shower-water-softener': typeof BestShowerWaterSoftenerRoute
  '/canopy-alternative-for-hard-water': typeof CanopyAlternativeForHardWaterRoute
  '/contact': typeof ContactRoute
  '/do-shower-filters-work-for-hard-water': typeof DoShowerFiltersWorkForHardWaterRoute
  '/jolie-alternative-for-hard-water': typeof JolieAlternativeForHardWaterRoute
  '/portable-water-softener-for-shower': typeof PortableWaterSoftenerForShowerRoute
  '/prevent-limescale-in-shower': typeof PreventLimescaleInShowerRoute
  '/reddit-shower-water-softener': typeof RedditShowerWaterSoftenerRoute
  '/returns': typeof ReturnsRoute
  '/setup': typeof SetupRoute
  '/shipping': typeof ShippingRoute
  '/shower-filter-vs-water-softener': typeof ShowerFilterVsWaterSoftenerRoute
  '/shower-head-water-softener': typeof ShowerHeadWaterSoftenerRoute
  '/showerstick-alternative': typeof ShowerstickAlternativeRoute
  '/softwatercare-vs-showerstick-vs-ag': typeof SoftwatercareVsShowerstickVsAgRoute
  '/spares-kit': typeof SparesKitRoute
  '/thanks': typeof ThanksRoute
  '/water-softener-for-apartment': typeof WaterSoftenerForApartmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arius-vs-ag-water-softener': typeof AriusVsAgWaterSoftenerRoute
  '/best-shower-water-softener': typeof BestShowerWaterSoftenerRoute
  '/canopy-alternative-for-hard-water': typeof CanopyAlternativeForHardWaterRoute
  '/contact': typeof ContactRoute
  '/do-shower-filters-work-for-hard-water': typeof DoShowerFiltersWorkForHardWaterRoute
  '/jolie-alternative-for-hard-water': typeof JolieAlternativeForHardWaterRoute
  '/portable-water-softener-for-shower': typeof PortableWaterSoftenerForShowerRoute
  '/prevent-limescale-in-shower': typeof PreventLimescaleInShowerRoute
  '/reddit-shower-water-softener': typeof RedditShowerWaterSoftenerRoute
  '/returns': typeof ReturnsRoute
  '/setup': typeof SetupRoute
  '/shipping': typeof ShippingRoute
  '/shower-filter-vs-water-softener': typeof ShowerFilterVsWaterSoftenerRoute
  '/shower-head-water-softener': typeof ShowerHeadWaterSoftenerRoute
  '/showerstick-alternative': typeof ShowerstickAlternativeRoute
  '/softwatercare-vs-showerstick-vs-ag': typeof SoftwatercareVsShowerstickVsAgRoute
  '/spares-kit': typeof SparesKitRoute
  '/thanks': typeof ThanksRoute
  '/water-softener-for-apartment': typeof WaterSoftenerForApartmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arius-vs-ag-water-softener'
    | '/best-shower-water-softener'
    | '/canopy-alternative-for-hard-water'
    | '/contact'
    | '/do-shower-filters-work-for-hard-water'
    | '/jolie-alternative-for-hard-water'
    | '/portable-water-softener-for-shower'
    | '/prevent-limescale-in-shower'
    | '/reddit-shower-water-softener'
    | '/returns'
    | '/setup'
    | '/shipping'
    | '/shower-filter-vs-water-softener'
    | '/shower-head-water-softener'
    | '/showerstick-alternative'
    | '/softwatercare-vs-showerstick-vs-ag'
    | '/spares-kit'
    | '/thanks'
    | '/water-softener-for-apartment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arius-vs-ag-water-softener'
    | '/best-shower-water-softener'
    | '/canopy-alternative-for-hard-water'
    | '/contact'
    | '/do-shower-filters-work-for-hard-water'
    | '/jolie-alternative-for-hard-water'
    | '/portable-water-softener-for-shower'
    | '/prevent-limescale-in-shower'
    | '/reddit-shower-water-softener'
    | '/returns'
    | '/setup'
    | '/shipping'
    | '/shower-filter-vs-water-softener'
    | '/shower-head-water-softener'
    | '/showerstick-alternative'
    | '/softwatercare-vs-showerstick-vs-ag'
    | '/spares-kit'
    | '/thanks'
    | '/water-softener-for-apartment'
  id:
    | '__root__'
    | '/'
    | '/arius-vs-ag-water-softener'
    | '/best-shower-water-softener'
    | '/canopy-alternative-for-hard-water'
    | '/contact'
    | '/do-shower-filters-work-for-hard-water'
    | '/jolie-alternative-for-hard-water'
    | '/portable-water-softener-for-shower'
    | '/prevent-limescale-in-shower'
    | '/reddit-shower-water-softener'
    | '/returns'
    | '/setup'
    | '/shipping'
    | '/shower-filter-vs-water-softener'
    | '/shower-head-water-softener'
    | '/showerstick-alternative'
    | '/softwatercare-vs-showerstick-vs-ag'
    | '/spares-kit'
    | '/thanks'
    | '/water-softener-for-apartment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AriusVsAgWaterSoftenerRoute: typeof AriusVsAgWaterSoftenerRoute
  BestShowerWaterSoftenerRoute: typeof BestShowerWaterSoftenerRoute
  CanopyAlternativeForHardWaterRoute: typeof CanopyAlternativeForHardWaterRoute
  ContactRoute: typeof ContactRoute
  DoShowerFiltersWorkForHardWaterRoute: typeof DoShowerFiltersWorkForHardWaterRoute
  JolieAlternativeForHardWaterRoute: typeof JolieAlternativeForHardWaterRoute
  PortableWaterSoftenerForShowerRoute: typeof PortableWaterSoftenerForShowerRoute
  PreventLimescaleInShowerRoute: typeof PreventLimescaleInShowerRoute
  RedditShowerWaterSoftenerRoute: typeof RedditShowerWaterSoftenerRoute
  ReturnsRoute: typeof ReturnsRoute
  SetupRoute: typeof SetupRoute
  ShippingRoute: typeof ShippingRoute
  ShowerFilterVsWaterSoftenerRoute: typeof ShowerFilterVsWaterSoftenerRoute
  ShowerHeadWaterSoftenerRoute: typeof ShowerHeadWaterSoftenerRoute
  ShowerstickAlternativeRoute: typeof ShowerstickAlternativeRoute
  SoftwatercareVsShowerstickVsAgRoute: typeof SoftwatercareVsShowerstickVsAgRoute
  SparesKitRoute: typeof SparesKitRoute
  ThanksRoute: typeof ThanksRoute
  WaterSoftenerForApartmentRoute: typeof WaterSoftenerForApartmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/water-softener-for-apartment': {
      id: '/water-softener-for-apartment'
      path: '/water-softener-for-apartment'
      fullPath: '/water-softener-for-apartment'
      preLoaderRoute: typeof WaterSoftenerForApartmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spares-kit': {
      id: '/spares-kit'
      path: '/spares-kit'
      fullPath: '/spares-kit'
      preLoaderRoute: typeof SparesKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/softwatercare-vs-showerstick-vs-ag': {
      id: '/softwatercare-vs-showerstick-vs-ag'
      path: '/softwatercare-vs-showerstick-vs-ag'
      fullPath: '/softwatercare-vs-showerstick-vs-ag'
      preLoaderRoute: typeof SoftwatercareVsShowerstickVsAgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showerstick-alternative': {
      id: '/showerstick-alternative'
      path: '/showerstick-alternative'
      fullPath: '/showerstick-alternative'
      preLoaderRoute: typeof ShowerstickAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-head-water-softener': {
      id: '/shower-head-water-softener'
      path: '/shower-head-water-softener'
      fullPath: '/shower-head-water-softener'
      preLoaderRoute: typeof ShowerHeadWaterSoftenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-filter-vs-water-softener': {
      id: '/shower-filter-vs-water-softener'
      path: '/shower-filter-vs-water-softener'
      fullPath: '/shower-filter-vs-water-softener'
      preLoaderRoute: typeof ShowerFilterVsWaterSoftenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reddit-shower-water-softener': {
      id: '/reddit-shower-water-softener'
      path: '/reddit-shower-water-softener'
      fullPath: '/reddit-shower-water-softener'
      preLoaderRoute: typeof RedditShowerWaterSoftenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prevent-limescale-in-shower': {
      id: '/prevent-limescale-in-shower'
      path: '/prevent-limescale-in-shower'
      fullPath: '/prevent-limescale-in-shower'
      preLoaderRoute: typeof PreventLimescaleInShowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portable-water-softener-for-shower': {
      id: '/portable-water-softener-for-shower'
      path: '/portable-water-softener-for-shower'
      fullPath: '/portable-water-softener-for-shower'
      preLoaderRoute: typeof PortableWaterSoftenerForShowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jolie-alternative-for-hard-water': {
      id: '/jolie-alternative-for-hard-water'
      path: '/jolie-alternative-for-hard-water'
      fullPath: '/jolie-alternative-for-hard-water'
      preLoaderRoute: typeof JolieAlternativeForHardWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/do-shower-filters-work-for-hard-water': {
      id: '/do-shower-filters-work-for-hard-water'
      path: '/do-shower-filters-work-for-hard-water'
      fullPath: '/do-shower-filters-work-for-hard-water'
      preLoaderRoute: typeof DoShowerFiltersWorkForHardWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canopy-alternative-for-hard-water': {
      id: '/canopy-alternative-for-hard-water'
      path: '/canopy-alternative-for-hard-water'
      fullPath: '/canopy-alternative-for-hard-water'
      preLoaderRoute: typeof CanopyAlternativeForHardWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-shower-water-softener': {
      id: '/best-shower-water-softener'
      path: '/best-shower-water-softener'
      fullPath: '/best-shower-water-softener'
      preLoaderRoute: typeof BestShowerWaterSoftenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arius-vs-ag-water-softener': {
      id: '/arius-vs-ag-water-softener'
      path: '/arius-vs-ag-water-softener'
      fullPath: '/arius-vs-ag-water-softener'
      preLoaderRoute: typeof AriusVsAgWaterSoftenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AriusVsAgWaterSoftenerRoute: AriusVsAgWaterSoftenerRoute,
  BestShowerWaterSoftenerRoute: BestShowerWaterSoftenerRoute,
  CanopyAlternativeForHardWaterRoute: CanopyAlternativeForHardWaterRoute,
  ContactRoute: ContactRoute,
  DoShowerFiltersWorkForHardWaterRoute: DoShowerFiltersWorkForHardWaterRoute,
  JolieAlternativeForHardWaterRoute: JolieAlternativeForHardWaterRoute,
  PortableWaterSoftenerForShowerRoute: PortableWaterSoftenerForShowerRoute,
  PreventLimescaleInShowerRoute: PreventLimescaleInShowerRoute,
  RedditShowerWaterSoftenerRoute: RedditShowerWaterSoftenerRoute,
  ReturnsRoute: ReturnsRoute,
  SetupRoute: SetupRoute,
  ShippingRoute: ShippingRoute,
  ShowerFilterVsWaterSoftenerRoute: ShowerFilterVsWaterSoftenerRoute,
  ShowerHeadWaterSoftenerRoute: ShowerHeadWaterSoftenerRoute,
  ShowerstickAlternativeRoute: ShowerstickAlternativeRoute,
  SoftwatercareVsShowerstickVsAgRoute: SoftwatercareVsShowerstickVsAgRoute,
  SparesKitRoute: SparesKitRoute,
  ThanksRoute: ThanksRoute,
  WaterSoftenerForApartmentRoute: WaterSoftenerForApartmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
